config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  resources :masters, controller: "masters"
  resources :prom_envs, controller: "prom_envs"
  resources :vik_envs, controller: "vik_envs"
  resources :viks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'masters#index'

end

app/models/vik_env.rb
class VikEnv < ApplicationRecord
end

app/controllers/vik_envs_controller.rb
class VikEnvsController < ApplicationController
  before_action :set_vik_env, only: [:show, :edit, :update, :destroy]

  # GET /vik_envs
  # GET /vik_envs.json
  def index
    @vik_envs = VikEnv.all
  end

  # GET /vik_envs/1
  # GET /vik_envs/1.json
  def show
  end

  # GET /vik_envs/new
  def new
    @vik_env = VikEnv.new
  end

  # GET /vik_envs/1/edit
  def edit
  end

  # POST /vik_envs
  # POST /vik_envs.json
  def create
    @vik_env = VikEnv.new(vik_env_params)

    respond_to do |format|
      if @vik_env.save
        format.html { redirect_to @vik_env, notice: 'Vik env was successfully created.' }
        format.json { render :show, status: :created, location: @vik_env }
      else
        format.html { render :new }
        format.json { render json: @vik_env.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vik_envs/1
  # PATCH/PUT /vik_envs/1.json
  def update
    respond_to do |format|
      if @vik_env.update(vik_env_params)
        format.html { redirect_to @vik_env, notice: 'Vik env was successfully updated.' }
        format.json { render :show, status: :ok, location: @vik_env }
      else
        format.html { render :edit }
        format.json { render json: @vik_env.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vik_envs/1
  # DELETE /vik_envs/1.json
  def destroy
    @vik_env.destroy
    respond_to do |format|
      format.html { redirect_to vik_envs_url, notice: 'Vik env was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vik_env
      @vik_env = VikEnv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vik_env_params
      params.require(:vik_env).permit(:environment, :description)
    end
end

app/helpers/vik_envs_helper.rb
module VikEnvsHelper
end

app/views/vik_envs/_form.html.erb
<%= form_with(model: vik_env, local: true) do |form| %>
  <% if vik_env.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vik_env.errors.count, "error") %> prohibited this vik_env from being saved:</h2>

      <ul>
      <% vik_env.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :environment %>
    <%= form.text_field :environment, id: :vik_env_environment %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :vik_env_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vik_envs/edit.html.erb
<h1>Editing Vik Env</h1>

<%= render 'form', vik_env: @vik_env %>

<%= link_to 'Show', @vik_env %> |
<%= link_to 'Back', vik_envs_path %>

app/views/vik_envs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vik Envs</h1>

<table>
  <thead>
    <tr>
      <th>Environment</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vik_envs.each do |vik_env| %>
      <tr>
        <td><%= vik_env.environment %></td>
        <td><%= vik_env.description %></td>
        <td><%= link_to 'Show', vik_env %></td>
        <td><%= link_to 'Edit', edit_vik_env_path(vik_env) %></td>
        <td><%= link_to 'Destroy', vik_env, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vik Env', new_vik_env_path %>

app/views/vik_envs/new.html.erb
<h1>New Vik Env</h1>

<%= render 'form', vik_env: @vik_env %>

<%= link_to 'Back', vik_envs_path %>

app/views/vik_envs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Environment:</strong>
  <%= @vik_env.environment %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vik_env.description %>
</p>

<%= link_to 'Edit', edit_vik_env_path(@vik_env) %> |
<%= link_to 'Back', vik_envs_path %>