config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  resources :masters, controller: "masters"
  resources :prom_envs, controller: "prom_envs"
  resources :vik_envs, controller: "vik_envs"
  resources :viks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'masters#index'

end

app/models/master.rb
class Master < ApplicationRecord
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  before_action :set_master, only: [:show, :edit, :update, :destroy]

  # GET /masters
  # GET /masters.json
  def index
    @masters = Master.all
  end

  # GET /masters/1
  # GET /masters/1.json
  def show
  end

  # GET /masters/new
  def new
    @master = Master.new
  end

  # GET /masters/1/edit
  def edit
  end

  # POST /masters
  # POST /masters.json
  def create
    @master = Master.new(master_params)

    respond_to do |format|
      if @master.save
        format.html { redirect_to @master, notice: 'Master was successfully created.' }
        format.json { render :show, status: :created, location: @master }
      else
        format.html { render :new }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masters/1
  # PATCH/PUT /masters/1.json
  def update
    respond_to do |format|
      if @master.update(master_params)
        format.html { redirect_to @master, notice: 'Master was successfully updated.' }
        format.json { render :show, status: :ok, location: @master }

        @vik_envs = VikEnv.all
        @vik_envs.each do |e|
          if @master.vikEnvironment = e.environment
            @vikDB = e.description
          end
        end

        @prom_envs = PromEnv.all
        @prom_envs.each do |e|
          if @master.promEnvironment = e.environment
            @promBD = e.description
    
          end
        end

        out_file = File.new("app/fileconfigs/VIK.exe.config", "w")
        out_file.puts(%Q[<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="loggingConfiguration" type="Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.LoggingSettings, Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" requirePermission="true" />
    <section name="exceptionHandling" type="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Configuration.ExceptionHandlingSettings, Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" requirePermission="true" />
    <section name="dataConfiguration" type="Microsoft.Practices.EnterpriseLibrary.Data.Configuration.DatabaseSettings, Microsoft.Practices.EnterpriseLibrary.Data, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" requirePermission="true" />
    <section name="cachingConfiguration" type="Microsoft.Practices.EnterpriseLibrary.Caching.Configuration.CacheManagerSettings, Microsoft.Practices.EnterpriseLibrary.Caching, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" requirePermission="true" />
  </configSections>
  <loggingConfiguration name="" tracingEnabled="true" defaultCategory="General">
    <listeners>
      <add name="Formatted EventLog TraceListener" type="Microsoft.Practices.EnterpriseLibrary.Logging.TraceListeners.FormattedEventLogTraceListener, Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        listenerDataType="Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.FormattedEventLogTraceListenerData, Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        source="Enterprise Library Logging" formatter="Text Formatter"
        log="Application" />
      <add name="Rolling Flat File Trace Listener" type="Microsoft.Practices.EnterpriseLibrary.Logging.TraceListeners.RollingFlatFileTraceListener, Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        listenerDataType="Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.RollingFlatFileTraceListenerData, Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        fileName="ExceptionLogs/VIK_Exceptions.log" formatter="Text Formatter" rollInterval="Day" rollSizeKB="10240" timeStampPattern="yyyy-MM-dd" maxArchivedFiles="10" />
      <add name="VIK4LogTranceListner" type="Microsoft.Practices.EnterpriseLibrary.Logging.Database.FormattedDatabaseTraceListener, Microsoft.Practices.EnterpriseLibrary.Logging.Database, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        listenerDataType="Microsoft.Practices.EnterpriseLibrary.Logging.Database.Configuration.FormattedDatabaseTraceListenerData, Microsoft.Practices.EnterpriseLibrary.Logging.Database, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        databaseInstanceName="VIK4Logs" writeLogStoredProcName="WriteLog"
        addCategoryStoredProcName="AddCategory" formatter="Text Formatter"
        traceOutputOptions="LogicalOperationStack, DateTime, Timestamp, ProcessId, ThreadId, Callstack" />
      <add name="Database Trace Listener" type="Microsoft.Practices.EnterpriseLibrary.Logging.Database.FormattedDatabaseTraceListener, Microsoft.Practices.EnterpriseLibrary.Logging.Database, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        listenerDataType="Microsoft.Practices.EnterpriseLibrary.Logging.Database.Configuration.FormattedDatabaseTraceListenerData, Microsoft.Practices.EnterpriseLibrary.Logging.Database, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        databaseInstanceName="LoggingDb" writeLogStoredProcName="WriteLog"
        addCategoryStoredProcName="AddCategory " formatter="Database Auditing Text Formatter"
        traceOutputOptions="None" filter="All" />
    </listeners>
    <formatters>
      <add type="Microsoft.Practices.EnterpriseLibrary.Logging.Formatters.TextFormatter, Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        template="Message: {message}{newline}" name="Text Formatter" />
      <add type="Microsoft.Practices.EnterpriseLibrary.Logging.Formatters.TextFormatter, Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        template="Title:{title}{newline}&#xA;Timestamp: {timestamp(local)}{newline}&#xA;Message: {message}{newline}"
        name="Auditing Text Formatter" />
      <add type="Microsoft.Practices.EnterpriseLibrary.Logging.Formatters.TextFormatter, Microsoft.Practices.EnterpriseLibrary.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        template="{message}"
        name="Database Auditing Text Formatter" />
    </formatters>
    <categorySources>
      <add switchValue="All" name="General" />
      <add switchValue="All" name="Trace">
        <listeners>
          <add name="Rolling Flat File Trace Listener" />
          <add name="Formatted EventLog TraceListener" />
        </listeners>
      </add>
      <add switchValue="All" name="VIKAuditing">
        <listeners>
          <add name="Database Trace Listener" />
        </listeners>
      </add>
    </categorySources>
    <specialSources>
      <allEvents switchValue="All" name="All Events" />
      <notProcessed switchValue="All" name="Unprocessed Category" />
      <errors switchValue="All" name="Logging Errors &amp; Warnings">
        <listeners>
          <add name="Formatted EventLog TraceListener" />
        </listeners>
      </errors>
    </specialSources>
  </loggingConfiguration>
  <exceptionHandling>
    <exceptionPolicies>
      <add name="CorePolicy">
        <exceptionTypes>
          <add name="Exception" type="System.Exception, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" postHandlingAction="ThrowNewException">
            <exceptionHandlers>
              <add name="Trace Handler" type="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging.LoggingExceptionHandler, Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" logCategory="Trace" eventId="100" severity="Error" title="VIK Exception Handling" formatterType="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.TextExceptionFormatter, Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" priority="0" useDefaultLogger="false" />
              <add name="Email Handler" type="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging.LoggingExceptionHandler, Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" logCategory="Email" eventId="100" severity="Error" title="Enterprise Library Exception Handling" formatterType="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.TextExceptionFormatter, Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" priority="0" useDefaultLogger="false" />
              <add name="Replace Handler" type="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.ReplaceHandler, Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=5.0.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" exceptionMessage="Application error. Please advise GIS and provide them with this error code: {handlingInstanceID}" replaceExceptionType="Crown.VIK.Common.VIKException, Crown.VIK.Common, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null" />
            </exceptionHandlers>
          </add>
        </exceptionTypes>
      </add>
    </exceptionPolicies>
  </exceptionHandling>
  <dataConfiguration defaultDatabase="VIKDb" />
  <connectionStrings>
    <add name="VIKDb" connectionString="Data Source=#{@vikDB};User Id=***;Password=***;Connect Timeout=30;pooling='true'; Max Pool Size=200;" providerName="System.Data.SqlClient" />

app/helpers/masters_helper.rb
module MastersHelper

end

app/views/masters/_form.html.erb
<%= form_with(model: master, local: true) do |form| %>
  <% if master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(master.errors.count, "error") %> prohibited this master from being saved:</h2>

      <ul>
      <% master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :viknum %>
    <%= form.text_field :viknum, id: :master_viknum %>
  </div>

  <div class="field">
    <%= form.label :vikEnvironment %>
    <%= form.text_field :vikEnvironment, id: :master_vikEnvironment %>
  </div>

  <div class="field">
    <%= form.label :promEnvironment %>
    <%= form.text_field :promEnvironment, id: :master_promEnvironment %>
  </div>

  <div class="field">
    <%= form.label :userID %>
    <%= form.text_field :userID, id: :master_userID %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :master_comment %>
  </div>

  <div class="field">
    <%= form.label :reqdt %>
    <%= form.date_select :reqdt, id: :master_reqdt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/masters/edit.html.erb
<h1>Editing <%= @master.viknum %></h1>

<%= render 'form', master: @master %>

<%= link_to 'Show', @master %> |
<%= link_to 'Back', masters_path %>

app/views/masters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Configurations</h1>

<div class="configs">

<% @masters.each do |master| %>
  <%= link_to edit_master_path(master) do %>
  <div class="vikContainer">
    <h1><%= master.viknum %></h1>
    <br>
    <br>
    <div>Vik DB:<%= master.vikEnvironment %></div>
    <div>Promotions DB:<%= master.promEnvironment %></div>
    <div> Required Until: <%= master.reqdt %></div>
    <br>
    <div><%= master.comment %></div>
    <br>
    <div>Updated At: </div>
    <div><%= master.updated_at %></div>

  </div>
  <% end %>
<% end %>

<%= link_to 'New Master', new_master_path %>

app/views/masters/new.html.erb
<h1>New Master</h1>

<%= render 'form', master: @master %>

<%= link_to 'Back', masters_path %>

app/views/masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Viknum:</strong>
  <%= @master.viknum %>
</p>

<p>
  <strong>Vikenvironment:</strong>
  <%= @master.vikEnvironment %>
</p>

<p>
  <strong>Promenvironment:</strong>
  <%= @master.promEnvironment %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @master.userID %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @master.comment %>
</p>

<p>
  <strong>Reqdt:</strong>
  <%= @master.reqdt %>
</p>

<%= link_to 'Edit', edit_master_path(@master) %> |
<%= link_to 'Back', masters_path %>