config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  resources :masters, controller: "masters"
  resources :prom_envs, controller: "prom_envs"
  resources :vik_envs, controller: "vik_envs"
  resources :viks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'masters#index'

end

app/models/prom_env.rb
class PromEnv < ApplicationRecord
end

app/controllers/prom_envs_controller.rb
class PromEnvsController < ApplicationController
  before_action :set_prom_env, only: [:show, :edit, :update, :destroy]

  # GET /prom_envs
  # GET /prom_envs.json
  def index
    @prom_envs = PromEnv.all
  end

  # GET /prom_envs/1
  # GET /prom_envs/1.json
  def show
  end

  # GET /prom_envs/new
  def new
    @prom_env = PromEnv.new
  end

  # GET /prom_envs/1/edit
  def edit
  end

  # POST /prom_envs
  # POST /prom_envs.json
  def create
    @prom_env = PromEnv.new(prom_env_params)

    respond_to do |format|
      if @prom_env.save
        format.html { redirect_to @prom_env, notice: 'Prom env was successfully created.' }
        format.json { render :show, status: :created, location: @prom_env }
      else
        format.html { render :new }
        format.json { render json: @prom_env.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prom_envs/1
  # PATCH/PUT /prom_envs/1.json
  def update
    respond_to do |format|
      if @prom_env.update(prom_env_params)
        format.html { redirect_to @prom_env, notice: 'Prom env was successfully updated.' }
        format.json { render :show, status: :ok, location: @prom_env }
      else
        format.html { render :edit }
        format.json { render json: @prom_env.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prom_envs/1
  # DELETE /prom_envs/1.json
  def destroy
    @prom_env.destroy
    respond_to do |format|
      format.html { redirect_to prom_envs_url, notice: 'Prom env was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prom_env
      @prom_env = PromEnv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prom_env_params
      params.require(:prom_env).permit(:environment, :description)
    end
end

app/helpers/prom_envs_helper.rb
module PromEnvsHelper
end

app/views/prom_envs/_form.html.erb
<%= form_with(model: prom_env, local: true) do |form| %>
  <% if prom_env.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prom_env.errors.count, "error") %> prohibited this prom_env from being saved:</h2>

      <ul>
      <% prom_env.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :environment %>
    <%= form.text_field :environment, id: :prom_env_environment %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :prom_env_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prom_envs/edit.html.erb
<h1>Editing Prom Env</h1>

<%= render 'form', prom_env: @prom_env %>

<%= link_to 'Show', @prom_env %> |
<%= link_to 'Back', prom_envs_path %>

app/views/prom_envs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prom Envs</h1>

<table>
  <thead>
    <tr>
      <th>Environment</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prom_envs.each do |prom_env| %>
      <tr>
        <td><%= prom_env.environment %></td>
        <td><%= prom_env.description %></td>
        <td><%= link_to 'Show', prom_env %></td>
        <td><%= link_to 'Edit', edit_prom_env_path(prom_env) %></td>
        <td><%= link_to 'Destroy', prom_env, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prom Env', new_prom_env_path %>

app/views/prom_envs/new.html.erb
<h1>New Prom Env</h1>

<%= render 'form', prom_env: @prom_env %>

<%= link_to 'Back', prom_envs_path %>

app/views/prom_envs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Environment:</strong>
  <%= @prom_env.environment %>
</p>

<p>
  <strong>Description:</strong>
  <%= @prom_env.description %>
</p>

<%= link_to 'Edit', edit_prom_env_path(@prom_env) %> |
<%= link_to 'Back', prom_envs_path %>