config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  resources :masters, controller: "masters"
  resources :prom_envs, controller: "prom_envs"
  resources :vik_envs, controller: "vik_envs"
  resources :viks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'masters#index'

end

app/models/vik.rb
class Vik < ApplicationRecord
end

app/controllers/viks_controller.rb
class ViksController < ApplicationController
  before_action :set_vik, only: [:show, :edit, :update, :destroy]

  # GET /viks
  # GET /viks.json
  def index
    @viks = Vik.all
  end

  # GET /viks/1
  # GET /viks/1.json
  def show
  end

  # GET /viks/new
  def new
    @vik = Vik.new
  end

  # GET /viks/1/edit
  def edit
  end

  # POST /viks
  # POST /viks.json
  def create
    @vik = Vik.new(vik_params)

    respond_to do |format|
      if @vik.save
        format.html { redirect_to @vik, notice: 'Vik was successfully created.' }
        format.json { render :show, status: :created, location: @vik }
      else
        format.html { render :new }
        format.json { render json: @vik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /viks/1
  # PATCH/PUT /viks/1.json
  def update
    respond_to do |format|
      if @vik.update(vik_params)
        format.html { redirect_to @vik, notice: 'Vik was successfully updated.' }
        format.json { render :show, status: :ok, location: @vik }
      else
        format.html { render :edit }
        format.json { render json: @vik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /viks/1
  # DELETE /viks/1.json
  def destroy
    @vik.destroy
    respond_to do |format|
      format.html { redirect_to viks_url, notice: 'Vik was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vik
      @vik = Vik.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vik_params
      params.require(:vik).permit(:name, :location)
    end
end

app/helpers/viks_helper.rb
module ViksHelper
end

app/views/viks/_form.html.erb
<%= form_with(model: vik, local: true) do |form| %>
  <% if vik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vik.errors.count, "error") %> prohibited this vik from being saved:</h2>

      <ul>
      <% vik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :vik_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :vik_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/viks/edit.html.erb
<h1>Editing Vik</h1>

<%= render 'form', vik: @vik %>

<%= link_to 'Show', @vik %> |
<%= link_to 'Back', viks_path %>

app/views/viks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Viks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @viks.each do |vik| %>
      <tr>
        <td><%= vik.name %></td>
        <td><%= vik.location %></td>
        <td><%= link_to 'Show', vik %></td>
        <td><%= link_to 'Edit', edit_vik_path(vik) %></td>
        <td><%= link_to 'Destroy', vik, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vik', new_vik_path %>

app/views/viks/new.html.erb
<h1>New Vik</h1>

<%= render 'form', vik: @vik %>

<%= link_to 'Back', viks_path %>

app/views/viks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vik.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @vik.location %>
</p>

<%= link_to 'Edit', edit_vik_path(@vik) %> |
<%= link_to 'Back', viks_path %>